// Seed initial destination data
import { db } from "./db";
import { destinations } from "@shared/schema";

const seedDestinations = [
  {
    name: "Santorini",
    country: "Greece",
    description: "Experience the iconic white-washed buildings, blue-domed churches, and stunning sunsets over the Aegean Sea. Santorini offers world-class wine, volcanic beaches, and romantic villages perched on dramatic cliffs.",
    imageUrl: "/assets/generated_images/Santorini_Greece_destination_ed8bbac7.png",
    category: "beach",
    featured: true,
    latitude: "36.3932",
    longitude: "25.4615",
    visaRequirements: "EU/Schengen visa required for most non-EU nationals. US, UK, Canada, Australia citizens can visit visa-free for up to 90 days within 180 days.",
    travelDocuments: "Valid passport (must be valid for at least 3 months beyond stay). Proof of accommodation and return ticket may be requested at border control.",
    climate: "Mediterranean climate with hot, dry summers and mild winters. Summer temperatures range from 25-30°C (77-86°F), perfect for beach activities. Winters are mild at 10-15°C (50-59°F) with occasional rain.",
    bestMonths: "April-May, September-October for pleasant weather and fewer crowds. July-August for beach season (hot and busy).",
  },
  {
    name: "Swiss Alps",
    country: "Switzerland",
    description: "Discover pristine alpine lakes, majestic snow-capped peaks, and charming mountain villages. Perfect for hiking, skiing, and experiencing breathtaking natural beauty in every season.",
    imageUrl: "/assets/generated_images/Mountain_lake_alpine_landscape_a7b30a6f.png",
    category: "mountain",
    featured: true,
    latitude: "46.5197",
    longitude: "8.0551",
    visaRequirements: "Schengen visa required for most non-EU nationals. US, UK, Canada, Australia, New Zealand citizens can visit visa-free for up to 90 days within 180 days.",
    travelDocuments: "Valid passport (must be valid for at least 3 months beyond departure date). Travel insurance is highly recommended. Proof of sufficient funds may be required.",
    climate: "Alpine climate with four distinct seasons. Summers (June-August) are warm at 15-25°C (59-77°F), ideal for hiking. Winters (December-March) are cold and snowy at -2 to 7°C (28-45°F), perfect for skiing. Spring and fall are mild but unpredictable.",
    bestMonths: "June-September for hiking and summer activities. December-March for skiing and winter sports. May and October for quieter visits with mild weather.",
  },
  {
    name: "Tokyo",
    country: "Japan",
    description: "Immerse yourself in a fascinating blend of ultra-modern technology and ancient traditions. Explore vibrant neighborhoods, savor incredible cuisine, and experience the unique Japanese culture in this dynamic metropolis.",
    imageUrl: "/assets/generated_images/Tokyo_Japan_city_nightscape_9823a378.png",
    category: "city",
    featured: true,
    latitude: "35.6762",
    longitude: "139.6503",
    visaRequirements: "Visa-free entry for citizens of 68 countries including US, UK, Canada, Australia for stays up to 90 days. Other nationals require a tourist visa from Japanese embassy/consulate.",
    travelDocuments: "Valid passport for duration of stay. Return or onward ticket. Declaration of health and customs form completed on arrival. Some travelers may need to show proof of sufficient funds.",
    climate: "Humid subtropical climate with hot, humid summers and mild winters. Summer temperatures reach 25-32°C (77-90°F) with high humidity. Winters are cool at 5-12°C (41-54°F) with occasional snow. Spring and autumn are comfortable.",
    bestMonths: "March-May for cherry blossoms and pleasant weather. September-November for fall foliage and mild temperatures. Avoid July-August (hot and humid) and rainy season (June-early July).",
  },
  {
    name: "Machu Picchu",
    country: "Peru",
    description: "Journey to the legendary Lost City of the Incas, perched high in the Andes Mountains. This archaeological wonder offers stunning mountain vistas and a glimpse into ancient civilization.",
    imageUrl: "/assets/generated_images/Machu_Picchu_Peru_ruins_7f99dac1.png",
    category: "cultural",
    featured: true,
    latitude: "-13.1631",
    longitude: "-72.5450",
    visaRequirements: "No visa required for US, UK, Canada, Australia, EU citizens for stays up to 90 days (tourist). Citizens of some countries require a consular visa before travel.",
    travelDocuments: "Valid passport (minimum 6 months validity). Machu Picchu entrance tickets must be purchased in advance. Tourist card (Tarjeta Andina de Migración) provided on arrival. Yellow fever vaccination certificate required if arriving from endemic areas.",
    climate: "Tropical mountain climate with wet and dry seasons. Dry season (May-September) has clear days at 12-20°C (54-68°F) but cold nights. Wet season (November-March) brings afternoon rain and warmer days at 16-22°C (61-72°F). High altitude means cool temperatures year-round.",
    bestMonths: "April-May, September-October for fewer crowds and good weather. June-August for driest conditions (peak tourist season). Avoid January-February (heavy rain can close Inca Trail).",
  },
  {
    name: "Cappadocia",
    country: "Turkey",
    description: "Float above fairy chimneys in a hot air balloon and explore underground cities carved into volcanic rock. This surreal landscape offers unique cave hotels and ancient history at every turn.",
    imageUrl: "/assets/generated_images/Cappadocia_Turkey_hot_air_balloons_52a3e247.png",
    category: "adventure",
    featured: true,
    latitude: "38.6431",
    longitude: "34.8289",
    visaRequirements: "E-visa available online for US, UK, Australia, China citizens (valid 180 days, allows 90-day stay). EU citizens can enter visa-free for up to 90 days. Some nationalities require consular visa.",
    travelDocuments: "Valid passport (minimum 6 months validity beyond entry date). E-visa printout if applicable. Proof of accommodation and return ticket may be requested. Travel insurance recommended.",
    climate: "Continental climate with hot, dry summers and cold, snowy winters. Summers (June-September) reach 25-35°C (77-95°F) with very low humidity. Winters (December-March) are freezing at -10 to 5°C (14-41°F) with frequent snowfall. Spring and autumn are mild.",
    bestMonths: "April-May, September-October for hot air balloon flights and comfortable temperatures. June-August for warm weather (peak season). December-February for winter wonderland scenery but very cold.",
  },
  {
    name: "Maldives",
    country: "Maldives",
    description: "Escape to a tropical paradise with crystal-clear turquoise waters, pristine white sand beaches, and luxurious overwater villas. Perfect for diving, snorkeling, and ultimate relaxation.",
    imageUrl: "/assets/generated_images/Maldives_overwater_bungalows_paradise_b727e2cb.png",
    category: "beach",
    featured: true,
    latitude: "3.2028",
    longitude: "73.2207",
    visaRequirements: "Free 30-day tourist visa on arrival for all nationalities. Can be extended up to 90 days. No pre-arranged visa required.",
    travelDocuments: "Valid passport (minimum 6 months validity). Confirmed hotel booking or resort reservation. Return/onward ticket. Sufficient funds for stay (credit card statement or cash). Completed health declaration and immigration arrival card.",
    climate: "Tropical monsoon climate with year-round warm temperatures at 25-31°C (77-88°F). Dry season (November-April) has calm seas and sunny skies. Wet season (May-October) brings afternoon rain and rougher seas but still warm. High humidity year-round.",
    bestMonths: "November-April for best weather, calm seas, and diving conditions. December-March is peak season (most expensive). May-October offers lower prices but possible rain and wind.",
  },
  {
    name: "Paris",
    country: "France",
    description: "Fall in love with the City of Light, home to the Eiffel Tower, Louvre Museum, and charming cafes. Experience world-class art, cuisine, and romance in one of Europe's most iconic cities.",
    imageUrl: "/assets/generated_images/Paris_Eiffel_Tower_twilight_4567ec69.png",
    category: "city",
    featured: false,
    latitude: "48.8566",
    longitude: "2.3522",
    visaRequirements: "Schengen visa required for most non-EU nationals. US, UK, Canada, Australia, Japan citizens can visit visa-free for up to 90 days within 180 days for tourism or business.",
    travelDocuments: "Valid passport (must be valid for at least 3 months beyond departure). Proof of accommodation in France. Travel insurance covering minimum €30,000 medical expenses (recommended). Return ticket and proof of sufficient funds may be required.",
    climate: "Temperate oceanic climate with mild temperatures year-round. Summers (June-August) are warm at 20-25°C (68-77°F). Winters (December-February) are cool at 3-8°C (37-46°F) with occasional frost. Spring and autumn are pleasant but rainy. Year-round possibility of rain.",
    bestMonths: "April-June, September-October for pleasant weather and fewer tourists. July-August for warmest temperatures (crowded). Avoid November-March for gray skies and cold, though December has festive markets.",
  },
  {
    name: "Serengeti",
    country: "Tanzania",
    description: "Witness the Great Migration and encounter Africa's incredible wildlife in their natural habitat. Experience unforgettable safari adventures across vast golden savannas under endless African skies.",
    imageUrl: "/assets/generated_images/African_safari_sunset_landscape_b72df65e.png",
    category: "adventure",
    featured: false,
    latitude: "-2.3333",
    longitude: "34.8333",
    visaRequirements: "Visa required for most nationalities. Available as e-visa online (recommended, $50 USD) or on arrival ($50-100 USD). US, UK, EU, Canada, Australia citizens eligible for visa on arrival.",
    travelDocuments: "Valid passport (minimum 6 months validity). Yellow fever vaccination certificate (mandatory if arriving from yellow fever endemic country, recommended for all). Proof of accommodation/safari booking and return ticket may be requested.",
    climate: "Tropical savanna climate with wet and dry seasons. Dry season (June-October) has warm days at 20-27°C (68-81°F) and cool nights. Short rains (November-December) and long rains (March-May) bring afternoon showers. Year-round mild temperatures but variable rainfall.",
    bestMonths: "June-October for Great Migration river crossings and best game viewing. January-February for calving season in southern Serengeti. Avoid April-May (heavy rains make roads difficult).",
  },
  {
    name: "Bali",
    country: "Indonesia",
    description: "Discover the Island of the Gods with its lush rice terraces, ancient temples, pristine beaches, and vibrant culture. Experience world-class surfing, traditional dance performances, and wellness retreats in this tropical paradise.",
    imageUrl: "/assets/generated_images/Bali_rice_terraces_paradise_ad9311d7.png",
    category: "beach",
    featured: true,
    latitude: "-8.3405",
    longitude: "115.0920",
    visaRequirements: "Visa-free entry for 30 days for citizens of 169 countries including US, UK, EU, Canada, Australia. Visa on arrival available for $35 USD (30 days, extendable once). E-visa also available online.",
    travelDocuments: "Valid passport (minimum 6 months validity and 2 blank pages). Return or onward ticket. Proof of accommodation. Customs declaration form on arrival.",
    climate: "Tropical climate with wet and dry seasons. Dry season (April-September) has sunny days at 27-30°C (81-86°F) with low humidity. Wet season (October-March) brings afternoon showers but still warm at 26-29°C (79-84°F). High humidity year-round.",
    bestMonths: "April-June, September for best weather and fewer crowds. July-August peak season (busy). Avoid January-February (heavy rain). December-March for surfing.",
  },
  {
    name: "Iceland",
    country: "Iceland",
    description: "Experience the land of fire and ice with otherworldly landscapes featuring volcanoes, glaciers, geysers, and stunning waterfalls. Chase the Northern Lights, relax in geothermal hot springs, and explore unique volcanic terrain.",
    imageUrl: "/assets/generated_images/Iceland_Northern_Lights_spectacle_d091315e.png",
    category: "adventure",
    featured: true,
    latitude: "64.9631",
    longitude: "-19.0208",
    visaRequirements: "Schengen visa required for most non-EU/EEA nationals. US, UK, Canada, Australia citizens can visit visa-free for up to 90 days within 180 days. No visa required for EU/EEA/Swiss citizens.",
    travelDocuments: "Valid passport (minimum 3 months validity beyond departure). Travel insurance highly recommended. Proof of sufficient funds and accommodation may be requested. International driving permit recommended for car rentals.",
    climate: "Subarctic climate with cool summers and relatively mild winters due to Gulf Stream. Summer (June-August) temperatures range 10-15°C (50-59°F) with near 24-hour daylight. Winter (November-March) is cold at -1 to 4°C (30-39°F) with short days. Year-round unpredictable weather.",
    bestMonths: "June-August for midnight sun, hiking, and accessible highlands. September-March for Northern Lights viewing. May and September for shoulder season (fewer crowds). Avoid November-February for short daylight hours.",
  },
  {
    name: "New York City",
    country: "United States",
    description: "Experience the city that never sleeps with its iconic skyline, world-class museums, Broadway shows, and diverse neighborhoods. From Central Park to Times Square, NYC offers endless entertainment, culture, and culinary adventures.",
    imageUrl: "/assets/generated_images/New_York_City_skyline_51e164b0.png",
    category: "city",
    featured: true,
    latitude: "40.7128",
    longitude: "-74.0060",
    visaRequirements: "ESTA (Electronic System for Travel Authorization) required for Visa Waiver Program countries (most EU, UK, Australia, Japan, etc.) - valid 2 years, $21 USD. Other nationals require US B-2 tourist visa from embassy/consulate. Canadians need valid passport only.",
    travelDocuments: "Valid passport (must be valid for duration of stay). ESTA approval or US visa. Return or onward ticket. Proof of sufficient funds. Customs and Border Protection forms.",
    climate: "Humid continental climate with four distinct seasons. Summers (June-August) are hot and humid at 25-30°C (77-86°F). Winters (December-February) are cold at -3 to 5°C (27-41°F) with snow. Spring and fall are mild and pleasant.",
    bestMonths: "April-June, September-November for comfortable weather and outdoor activities. December for holiday atmosphere and lights. Avoid July-August (hot and humid) and January-February (coldest with snow).",
  },
  {
    name: "Dubai",
    country: "United Arab Emirates",
    description: "Marvel at futuristic skyscrapers, luxury shopping, and world-record attractions in this desert metropolis. From the Burj Khalifa to indoor skiing, Dubai combines Arabian culture with ultra-modern innovation and opulence.",
    imageUrl: "/assets/generated_images/Dubai_modern_skyline_2ee63a52.png",
    category: "city",
    featured: true,
    latitude: "25.2048",
    longitude: "55.2708",
    visaRequirements: "Visa on arrival (free, 30 days) for citizens of 50+ countries including US, UK, EU, Canada, Australia. E-visa available online for other eligible nationalities ($100-250 USD). Some countries require pre-arranged visa.",
    travelDocuments: "Valid passport (minimum 6 months validity). Return or onward ticket. Proof of accommodation. Travel insurance recommended. No Israeli passport stamps allowed.",
    climate: "Hot desert climate with extremely hot summers and warm winters. Summer (May-September) is scorching at 35-45°C (95-113°F) with high humidity. Winter (November-March) is pleasant at 20-30°C (68-86°F). Minimal rainfall year-round.",
    bestMonths: "November-March for comfortable weather and outdoor activities. December-February is peak season (busy). Avoid June-August (extreme heat). April and October are transitional (warm but manageable).",
  },
  {
    name: "Bora Bora",
    country: "French Polynesia",
    description: "Indulge in the ultimate tropical luxury with crystal-clear lagoons, pristine coral reefs, and overwater bungalows. This island paradise offers world-class snorkeling, diving, and romance in an unforgettable setting.",
    imageUrl: "/assets/generated_images/Bora_Bora_luxury_paradise_2fa98a83.png",
    category: "beach",
    featured: false,
    latitude: "-16.5004",
    longitude: "-151.7415",
    visaRequirements: "Visa-free entry for up to 90 days for citizens of US, UK, EU, Canada, Australia, and many other countries. French territory visa rules apply. Extended stays require French long-stay visa.",
    travelDocuments: "Valid passport (minimum 6 months validity beyond stay). Return or onward ticket. Proof of sufficient funds. Accommodation confirmation. Health insurance recommended.",
    climate: "Tropical oceanic climate with warm temperatures year-round. Dry season (May-October) has sunny days at 24-28°C (75-82°F) with gentle trade winds. Wet season (November-April) brings occasional rain but still warm at 26-30°C (79-86°F).",
    bestMonths: "May-October for best weather, calm seas, and ideal water conditions. June-August is peak season (expensive). November-April offers lower prices but possible rain. Year-round warm swimming.",
  },
  {
    name: "Petra",
    country: "Jordan",
    description: "Step into ancient history at the rose-red city carved into sandstone cliffs over 2,000 years ago. This UNESCO World Heritage Site offers breathtaking archaeology, desert landscapes, and Nabataean culture.",
    imageUrl: "/assets/generated_images/Petra_Jordan_ancient_wonder_67373cb2.png",
    category: "cultural",
    featured: true,
    latitude: "30.3285",
    longitude: "35.4444",
    visaRequirements: "Visa required for most nationalities. Visa on arrival available at Queen Alia Airport ($40-120 USD depending on nationality). Jordan Pass recommended (includes visa fee + entry to Petra and other sites). Free visa for visits over 2 nights.",
    travelDocuments: "Valid passport (minimum 6 months validity). Jordan Pass or visa on arrival. Proof of accommodation. Return ticket may be requested. Travel insurance recommended.",
    climate: "Hot desert climate with extreme temperature variations. Summer (June-August) is very hot at 30-35°C (86-95°F) but dry. Winter (December-February) is mild during day 10-15°C (50-59°F) but cold at night. Spring and fall are ideal. Minimal rainfall.",
    bestMonths: "March-May, September-November for comfortable temperatures and clear skies. Avoid June-August (extreme heat makes walking difficult). December-February can be cold and occasionally rainy but fewer tourists.",
  },
  {
    name: "Venice",
    country: "Italy",
    description: "Navigate the romantic canals of this unique floating city built on 118 islands. Experience gondola rides, stunning Byzantine architecture, world-renowned art, and the magic of a car-free historic center.",
    imageUrl: "/assets/generated_images/Venice_Grand_Canal_romance_1873c041.png",
    category: "city",
    featured: false,
    latitude: "45.4408",
    longitude: "12.3155",
    visaRequirements: "Schengen visa required for most non-EU nationals. US, UK, Canada, Australia, Japan citizens can visit visa-free for up to 90 days within 180 days. EU citizens need valid ID/passport only.",
    travelDocuments: "Valid passport (minimum 3 months validity beyond departure). Travel insurance covering €30,000 medical expenses (recommended). Proof of accommodation and return ticket may be requested. Venice tourist tax payable (€3-10 per night).",
    climate: "Humid subtropical climate with hot summers and cool winters. Summer (June-August) is hot and humid at 25-30°C (77-86°F). Winter (December-February) is cool and foggy at 3-8°C (37-46°F) with occasional flooding (acqua alta). Spring and fall are pleasant.",
    bestMonths: "April-May, September-October for comfortable weather and manageable crowds. June-August for warmest weather (very crowded and expensive). Avoid November-January for fog, cold, and flooding risk.",
  },
  {
    name: "Norwegian Fjords",
    country: "Norway",
    description: "Cruise through dramatic landscapes of deep blue fjords flanked by towering cliffs, cascading waterfalls, and charming villages. Experience pristine nature, midnight sun, and outdoor adventures in Norway's most scenic region.",
    imageUrl: "/assets/generated_images/Norwegian_Fjords_majesty_3650d278.png",
    category: "mountain",
    featured: false,
    latitude: "61.0000",
    longitude: "7.0000",
    visaRequirements: "Schengen visa required for most non-EU/EEA nationals. US, UK, Canada, Australia citizens can visit visa-free for up to 90 days within 180 days. No visa for EU/EEA/Swiss citizens.",
    travelDocuments: "Valid passport (minimum 3 months validity beyond departure). Travel insurance highly recommended. Proof of sufficient funds and accommodation may be requested. International driving permit useful for car rentals.",
    climate: "Oceanic and subarctic climate moderated by Gulf Stream. Summer (June-August) has mild temperatures at 15-20°C (59-68°F) with long daylight. Winter (December-February) is cold at -5 to 3°C (23-37°F) with short days and snow. Year-round rain possible.",
    bestMonths: "May-September for best weather, midnight sun, and accessible hiking. June-July for longest days and wildflowers. September for fall colors and Northern Lights. Winter for snow sports but limited daylight.",
  },
  {
    name: "Barcelona",
    country: "Spain",
    description: "Immerse yourself in Gaudí's architectural masterpieces, Mediterranean beaches, vibrant nightlife, and world-class cuisine. This Catalan capital perfectly blends historic charm with modern innovation and coastal beauty.",
    imageUrl: "/assets/generated_images/Barcelona_Sagrada_Familia_beauty_f7173a26.png",
    category: "city",
    featured: false,
    latitude: "41.3851",
    longitude: "2.1734",
    visaRequirements: "Schengen visa required for most non-EU nationals. US, UK, Canada, Australia, Japan citizens can visit visa-free for up to 90 days within 180 days. EU citizens need valid ID/passport only.",
    travelDocuments: "Valid passport (minimum 3 months validity beyond departure). Travel insurance covering €30,000 medical expenses (recommended). Proof of accommodation and return ticket may be requested. Sufficient funds for stay.",
    climate: "Mediterranean climate with mild winters and warm summers. Summer (June-September) is warm at 25-30°C (77-86°F) with beach weather. Winter (December-February) is mild at 10-15°C (50-59°F). Spring and fall are pleasant. Low rainfall year-round.",
    bestMonths: "May-June, September-October for warm weather and fewer crowds. July-August for beach season (hot and crowded). December-March for mild winters and cultural exploration. Avoid peak summer for better prices.",
  },
  {
    name: "Great Barrier Reef",
    country: "Australia",
    description: "Dive into the world's largest coral reef system with vibrant marine life, pristine waters, and unparalleled underwater biodiversity. Experience snorkeling, diving, and island hopping in this natural wonder.",
    imageUrl: "/assets/generated_images/Great_Barrier_Reef_underwater_37741a95.png",
    category: "beach",
    featured: false,
    latitude: "-18.2871",
    longitude: "147.6992",
    visaRequirements: "eVisitor (free) for EU citizens. ETA (Electronic Travel Authority, $20 AUD) for US, UK, Canada, Japan, Korea citizens. Tourist visa required for other nationalities ($145-1020 AUD). Apply online before travel.",
    travelDocuments: "Valid passport (for duration of stay). Approved visa/ETA. Return or onward ticket. Proof of sufficient funds. Completed Incoming Passenger Card. Marine park fees apply for reef visits.",
    climate: "Tropical climate with wet and dry seasons. Dry season (April-November) has sunny days at 23-28°C (73-82°F) and excellent visibility. Wet season (December-March) brings rain, humidity, and possible cyclones at 28-32°C (82-90°F).",
    bestMonths: "June-October for best visibility, calm seas, and ideal diving conditions. April-May and November for shoulder season. Avoid December-March (jellyfish season, cyclones, and heavy rain).",
  },
  {
    name: "Banff",
    country: "Canada",
    description: "Explore the Canadian Rockies with pristine turquoise lakes, majestic mountain peaks, abundant wildlife, and endless outdoor adventures. From skiing to hiking, Banff offers year-round natural beauty and adventure.",
    imageUrl: "/assets/generated_images/Banff_Lake_Louise_scenery_8ee5ffa7.png",
    category: "mountain",
    featured: true,
    latitude: "51.4968",
    longitude: "-115.9281",
    visaRequirements: "eTA (Electronic Travel Authorization, $7 CAD) required for visa-exempt foreign nationals arriving by air (includes US, UK, EU, Australia). Valid up to 5 years. Some nationalities require visitor visa. US citizens need valid passport only.",
    travelDocuments: "Valid passport (for duration of stay). eTA or visitor visa. Proof of sufficient funds. Return ticket. Parks Canada pass required for national park entry ($10 CAD/day or $70 CAD/year).",
    climate: "Subarctic climate with short summers and long, cold winters. Summer (June-August) is mild at 10-25°C (50-77°F) ideal for hiking. Winter (November-April) is very cold at -15 to -5°C (5-23°F) with heavy snow for skiing. Spring and fall are cool.",
    bestMonths: "July-August for warmest weather and accessible hiking trails. December-March for skiing and winter sports. September for fall colors and fewer crowds. Avoid April-May (snow melting, roads closed).",
  },
  {
    name: "Marrakech",
    country: "Morocco",
    description: "Lose yourself in the vibrant souks, stunning palaces, and exotic gardens of this imperial city. Experience rich Moroccan culture, aromatic spices, traditional riads, and the gateway to the Sahara Desert.",
    imageUrl: "/assets/generated_images/Marrakech_vibrant_medina_4e71d73e.png",
    category: "cultural",
    featured: false,
    latitude: "31.6295",
    longitude: "-7.9811",
    visaRequirements: "Visa-free entry for 90 days for citizens of US, UK, EU, Canada, Australia, and many other countries. Passport stamped on arrival. Extended stays require visa from Moroccan embassy.",
    travelDocuments: "Valid passport (minimum 6 months validity beyond departure date). Return or onward ticket. Proof of accommodation. Customs declaration form. Sufficient funds for stay.",
    climate: "Hot semi-arid climate with hot summers and mild winters. Summer (June-August) is very hot at 35-40°C (95-104°F). Winter (November-March) is pleasant at 18-22°C (64-72°F) with cool nights. Spring and fall are ideal. Minimal rainfall.",
    bestMonths: "March-May, September-November for comfortable temperatures and pleasant weather. December-February for mild days and cool nights. Avoid June-August (extreme heat makes sightseeing difficult).",
  },
];

export async function seedDatabase() {
  try {
    console.log("Seeding destinations...");
    
    // Check if we have all destinations (should be 20 total)
    const existing = await db.select().from(destinations);
    const existingCount = existing.length;
    const expectedCount = seedDestinations.length;
    
    if (existingCount === expectedCount) {
      console.log(`All ${expectedCount} destinations already seeded, skipping...`);
      return;
    }
    
    if (existingCount > 0 && existingCount < expectedCount) {
      console.log(`Found ${existingCount} destinations, but expected ${expectedCount}. Adding missing destinations...`);
      
      // Get existing destination names to avoid duplicates
      const existingNames = existing.map(d => d.name);
      const missingDestinations = seedDestinations.filter(d => !existingNames.includes(d.name));
      
      if (missingDestinations.length > 0) {
        await db.insert(destinations).values(missingDestinations);
        console.log(`Successfully added ${missingDestinations.length} missing destinations`);
      }
      return;
    }

    // No destinations exist, insert all
    await db.insert(destinations).values(seedDestinations);
    console.log(`Successfully seeded ${seedDestinations.length} destinations`);
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}
